import time
import asyncio
from backend.app.langgraph.state import GraphState
from backend.app.services.search_service import SearchService
from backend.app.core.logging import logger

async def research_node(state: GraphState) -> dict:
    """
    Research Node:
    Iterates over the queries generated by the Planner and queries the SearchService (Tavily).
    Deduplicates results by URL.
    """
    logger.info(f"--- STARTING RESEARCH NODE for: {state['company_name']} ---")
    start_time = time.time()
    
    search_service = SearchService()
    
    # Retrieve the search plan queries
    queries = state.get("search_plan", [])
    if not queries:
        logger.warning("No search plan found in graph state. Using fallback queries.")
        queries = [f"{state['company_name']} business details overview"]
        
    all_results = []
    
    # Run searches sequentially or concurrently. To respect API rates and keep logging clean, we run sequentially
    # but with a short async sleep if needed.
    for query in queries:
        try:
            results = await search_service.search(query, max_results=3)
            all_results.extend(results)
        except Exception as e:
            logger.error(f"Search failed for query '{query}': {e}")
            
    # Deduplicate results by URL
    seen_urls = set()
    deduped_results = []
    
    # Keep track of existing results in state if this is a retry loop
    existing_results = state.get("search_results", []) or []
    for res in existing_results:
        url = res.get("url")
        if url:
            seen_urls.add(url)
            deduped_results.append(res)
            
    for res in all_results:
        url = res.get("url")
        if url and url not in seen_urls:
            seen_urls.add(url)
            deduped_results.append(res)
            
    # Determine retry count increment
    # If we already have search results, it means we looped back from Quality Check
    current_retry = state.get("retry_count", 0)
    if existing_results:
        current_retry += 1
        logger.info(f"Research node is executing in RETRY loop. Incrementing retry count to {current_retry}")

    execution_time = round(time.time() - start_time, 2)
    metrics = state.get("execution_metrics", {}) or {}
    metrics["research"] = execution_time
    
    logger.info(f"Research finished in {execution_time}s. Collected {len(deduped_results)} unique sources.")
    
    return {
        "search_results": deduped_results,
        "status": "researching",
        "retry_count": current_retry,
        "execution_metrics": metrics
    }
